---
- name: Install remi repository
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present

- name: Install epel repository
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

- name: Install php7.1
  yum: name={{ item }} state=present enablerepo=remi,remi-php71
  with_items:
    - php
    - php-fpm
    - php-mysqlnd
    - php-mbstring
    - php-mcrypt
    # - php-pear
    # - php-gd
    # - php-pecl-xdebug
    # - php-opcache
    # - php-pecl-memcached
  notify:
  #  - Restart nginx
   - Restart php-fpm

# - name: Upload php.ini
#   template: src=php.ini dest=/etc/php.ini
#   notify: Restart php-fpm

# - name: Upload www.conf
#   template: src=www.conf dest=/etc/php-fpm.d/www.conf

- name: Start & Enabled php-fpm
  service: name=php-fpm state=running enabled=yes
